--------------------------------------------------------
--  Fichier créé - mercredi-février-26-2025   
--------------------------------------------------------
DROP TABLE "YOUSSEF"."EMPLOYE";
DROP TABLE "YOUSSEF"."ESPACE";
DROP TABLE "YOUSSEF"."EVENEMENT";
DROP TABLE "YOUSSEF"."LOCATAIRE";
DROP TABLE "YOUSSEF"."MAINTENANCE";
DROP TABLE "YOUSSEF"."SERVICE";
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."EMPLOYE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(200 BYTE), 
	"PRENOM" VARCHAR2(200 BYTE), 
	"DATE_EMBAUCHE" DATE DEFAULT sysdate, 
	"POSTE" VARCHAR2(200 BYTE), 
	"SALAIRE" NUMBER DEFAULT 0, 
	"EMAIL" VARCHAR2(200 BYTE), 
	"SEXE" VARCHAR2(200 BYTE), 
	"TELEPHONE" NUMBER, 
	"STATUT" VARCHAR2(200 BYTE), 
	"FACE_ID" BLOB, 
	"EMPREINTE" BLOB, 
	"PDP" BLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("FACE_ID") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("EMPREINTE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("PDP") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table ESPACE
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."ESPACE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(200 BYTE), 
	"TYPE" VARCHAR2(200 BYTE), 
	"SUPERFICIE" NUMBER, 
	"EMPLACEMENT" VARCHAR2(200 BYTE), 
	"STATUT" VARCHAR2(200 BYTE), 
	"LOYER_M" NUMBER, 
	"DATE_DEB_CONTRAT" DATE, 
	"ID_LOCATAIRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EVENEMENT
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."EVENEMENT" 
   (	"ID" NUMBER, 
	"TITRE" VARCHAR2(200 BYTE), 
	"TYPE" VARCHAR2(200 BYTE), 
	"CAPACITE" NUMBER, 
	"PRIX" NUMBER, 
	"AFFICHE" BLOB, 
	"DESCRIPTION" LONG, 
	"DATE_DEB" DATE, 
	"DATE_FIN" DATE, 
	"CATEGORIE" VARCHAR2(200 BYTE), 
	"STATUT" VARCHAR2(200 BYTE), 
	"ORGANISATEUR" VARCHAR2(200 BYTE), 
	"ID_ESPACE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("AFFICHE") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table LOCATAIRE
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."LOCATAIRE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(200 BYTE), 
	"PRENOM" VARCHAR2(200 BYTE), 
	"TYPR_ACTIVITE" VARCHAR2(200 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"TELEPHONE" NUMBER, 
	"CONTRAT" BLOB, 
	"DUREE_CONTRAT" VARCHAR2(200 BYTE), 
	"DATE_DEB" DATE, 
	"DATE_FIN" DATE, 
	"PAIMENT_EFFECTUE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTRAT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table MAINTENANCE
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."MAINTENANCE" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" LONG, 
	"COUT" NUMBER, 
	"STATUT" VARCHAR2(200 BYTE), 
	"DATE_RESOLUTION" VARCHAR2(20 BYTE), 
	"ID_EMPLOYE" NUMBER, 
	"ID_ESPACE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SERVICE
--------------------------------------------------------

  CREATE TABLE "YOUSSEF"."SERVICE" 
   (	"ID" NUMBER, 
	"NOM" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(2000 BYTE), 
	"STATU" VARCHAR2(20 BYTE), 
	"COUT" NUMBER, 
	"FREQUENCE" VARCHAR2(20 BYTE), 
	"DATE_DEB" DATE DEFAULT sysdate, 
	"DATE_FIN" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into YOUSSEF.EMPLOYE
SET DEFINE OFF;
REM INSERTING into YOUSSEF.ESPACE
SET DEFINE OFF;
REM INSERTING into YOUSSEF.EVENEMENT
SET DEFINE OFF;
REM INSERTING into YOUSSEF.LOCATAIRE
SET DEFINE OFF;
REM INSERTING into YOUSSEF.MAINTENANCE
SET DEFINE OFF;
REM INSERTING into YOUSSEF.SERVICE
SET DEFINE OFF;
Insert into YOUSSEF.SERVICE (ID,NOM,DESCRIPTION,STATU,COUT,FREQUENCE,DATE_DEB,DATE_FIN) values (1,'wifi','service gratuit','actif',5000,'mensuel',to_date('26-02-25','DD-MM-RR'),to_date('18-02-28','DD-MM-RR'));
Insert into YOUSSEF.SERVICE (ID,NOM,DESCRIPTION,STATU,COUT,FREQUENCE,DATE_DEB,DATE_FIN) values (2,'parking','hhhhhh','suspendu',20000,'hebdomaadaire',to_date('26-02-25','DD-MM-RR'),to_date('26-02-27','DD-MM-RR'));
--------------------------------------------------------
--  DDL for Index PK_EMPLOYE
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."PK_EMPLOYE" ON "YOUSSEF"."EMPLOYE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ESPACE
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."PK_ESPACE" ON "YOUSSEF"."ESPACE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EVENEMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."PK_EVENEMENT" ON "YOUSSEF"."EVENEMENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LOCATAIRE
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."PK_LOCATAIRE" ON "YOUSSEF"."LOCATAIRE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MAINTENANCE
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."PK_MAINTENANCE" ON "YOUSSEF"."MAINTENANCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_SERVICE
--------------------------------------------------------

  CREATE UNIQUE INDEX "YOUSSEF"."PK_SERVICE" ON "YOUSSEF"."SERVICE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."EMPLOYE" ADD CONSTRAINT "PK_EMPLOYE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("PDP" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("EMPREINTE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("FACE_ID" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("STATUT" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("SEXE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("POSTE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("DATE_EMBAUCHE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EMPLOYE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESPACE
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."ESPACE" MODIFY ("ID_LOCATAIRE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."ESPACE" ADD CONSTRAINT "PK_ESPACE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOUSSEF"."ESPACE" MODIFY ("DATE_DEB_CONTRAT" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."ESPACE" MODIFY ("LOYER_M" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."ESPACE" MODIFY ("STATUT" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."ESPACE" MODIFY ("EMPLACEMENT" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."ESPACE" MODIFY ("SUPERFICIE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."ESPACE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."ESPACE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."ESPACE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENEMENT
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("ID_ESPACE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EVENEMENT" ADD CONSTRAINT "PK_EVENEMENT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("ORGANISATEUR" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("STATUT" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("CATEGORIE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("DATE_FIN" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("DATE_DEB" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("AFFICHE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("CAPACITE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("TITRE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."EVENEMENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOCATAIRE
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."LOCATAIRE" ADD CONSTRAINT "PK_LOCATAIRE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOUSSEF"."LOCATAIRE" MODIFY ("PAIMENT_EFFECTUE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."LOCATAIRE" MODIFY ("DATE_FIN" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."LOCATAIRE" MODIFY ("DATE_DEB" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."LOCATAIRE" MODIFY ("DUREE_CONTRAT" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."LOCATAIRE" MODIFY ("CONTRAT" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."LOCATAIRE" MODIFY ("TELEPHONE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."LOCATAIRE" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."LOCATAIRE" MODIFY ("TYPR_ACTIVITE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."LOCATAIRE" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."LOCATAIRE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."LOCATAIRE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MAINTENANCE
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."MAINTENANCE" MODIFY ("ID_ESPACE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."MAINTENANCE" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."MAINTENANCE" ADD CONSTRAINT "PK_MAINTENANCE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOUSSEF"."MAINTENANCE" MODIFY ("DATE_RESOLUTION" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."MAINTENANCE" MODIFY ("STATUT" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."MAINTENANCE" MODIFY ("COUT" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."MAINTENANCE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."MAINTENANCE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."MAINTENANCE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SERVICE
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."SERVICE" ADD CONSTRAINT "PK_SERVICE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "YOUSSEF"."SERVICE" MODIFY ("DATE_FIN" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."SERVICE" MODIFY ("DATE_DEB" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."SERVICE" MODIFY ("FREQUENCE" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."SERVICE" MODIFY ("COUT" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."SERVICE" MODIFY ("STATU" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."SERVICE" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."SERVICE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "YOUSSEF"."SERVICE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ESPACE
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."ESPACE" ADD CONSTRAINT "FK_LOCATAIRE" FOREIGN KEY ("ID_LOCATAIRE")
	  REFERENCES "YOUSSEF"."LOCATAIRE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EVENEMENT
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."EVENEMENT" ADD CONSTRAINT "FK_ESPACE" FOREIGN KEY ("ID_ESPACE")
	  REFERENCES "YOUSSEF"."ESPACE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MAINTENANCE
--------------------------------------------------------

  ALTER TABLE "YOUSSEF"."MAINTENANCE" ADD CONSTRAINT "FK_EMPLOYE" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "YOUSSEF"."EMPLOYE" ("ID") ENABLE;
  ALTER TABLE "YOUSSEF"."MAINTENANCE" ADD CONSTRAINT "FK_ESPACES" FOREIGN KEY ("ID_ESPACE")
	  REFERENCES "YOUSSEF"."ESPACE" ("ID") ENABLE;
